name: Run Nodejs Script

on: push

jobs:
  run-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts'

      - name: Run app.js
        run: node app.js
