name: hello-world

on: push

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Hello Nabed"
        
      - name: Show Vbuntu Version
        run: lsb_release -a

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check Node Version
        run: node -v

      - name: Check NPM Version
        run: npm -v
